from argschema.fields import Bool, Float, Int, Nested, Str, InputDir
from argschema.schemas import DefaultSchema


class PointMatchOptimizationParameters(DefaultSchema):
    baseCanvasUrl = Str(
        required=True,
        description="Base URL for canvas data (e.g. http://host[:port]/render-ws/v1/owner/gayathri/project/MM2/stack/mm2_acquire_8bit_reimage/tile)")
    pId = Str(
        required=True,
        description="Identifier for P canvas")
    qId = Str(
        required=True,
        description="Identifier for Q canvas")
    renderScaleStep = Float(
        required=False,
        default=0.1,
        missing=0.1,
        description="Amount to adjust render scale for each iteration during optimization")
    minFeatureCount = Int(
        required=False,
        default=3000,
        missing=3000,
        description="Minimum number of features for optimal render scale")
    maxFeatureCount = Int(
        required=False,
        default=6000,
        missing=6000,
        description="Maximum number of features for optimal render scale")
    SIFTfdSize = Int(
        required=False,
        default=8,
        missing=8,
        description="SIFT feature descriptor size: how many sample per row and column")
    SIFTsteps = Int(
        required=False,
        default=2,
        missing=2,
        description="SIFT steps per scale octave")
    matchModelType = Str(
        required=False,
        default="AFFINE",
        missing="AFFINE",
        description="Type of model for match filtering")
    matchIterations = Int(
        required=False,
        default=1000,
        missing=1000,
        description="Match filter iterations")
    matchMaxEpsilon = Float(
        required=False,
        default=20.0,
        missing=20.0,
        description="Minimal allowed transfer error for match filtering")
    matchMinInlierRatio = Float(
        required=False,
        default=0.0,
        missing=0.0,
        description="Minimal ratio of inliers to candidates for match filtering")
    matchMinNumInliers = Int(
        required=False,
        default=10,
        missing=10,
        description="Minimal absolute number of inliers for match filtering")
    matchMaxTrust = Float(
        required=False,
        default=3.0,
        missing=3.0,
        description="Reject match candidates with a cost larger than maxTrust * media cost")
    matchMaxNumInliers = Int(
        required=False,
        default=200,
        missing=200,
        descripton="Maximum number of inliers for match filtering")
    matchRodStep = Float(
        required=False,
        default=0.05,
        missing=0.05,
        description="AMount to adjust ratio of distances for each iteration during optimization")
