import os

pool_size = os.environ.get('ASAP_POOL_SIZE', 5)

MATERIALIZED_IMAGE_WIDTH = os.environ.get(
    'ASAP_MATERIALIZED_IMAGE_WIDTH', 256)
MATERIALIZED_IMAGE_HEIGHT = os.environ.get(
    'ASAP_MATERIALIZED_IMAGE_HEIGHT', 256)
MATERIALIZED_PROJECT = os.environ.get(
    'ASAP_MATERIALIZED_PROJECT', "dummy_project")
MATERIALIZED_STACK = os.environ.get(
    'ASAP_MATERIALIZED_STACK', "dummy_stack")
MATERIALIZED_MINROW = os.environ.get(
    'ASAP_MATERIALIZED_MINROW', 60)
MATERIALIZED_MINCOL = os.environ.get(
    'ASAP_MATERIALIZED_MINCOL', 40)
MATERIALIZED_MAXROW = os.environ.get(
    'ASAP_MATERIALIZED_MAXROW', 62)
MATERIALIZED_MAXCOL = os.environ.get(
    'ASAP_MATERIALIZED_MAXCOL', 41)
MATERIALIZED_MINZ = os.environ.get(
    'ASAP_MATERIALIZED_MINZ', 10)
MATERIALIZED_MAXZ = os.environ.get(
    'ASAP_MATERIALIZED_MAXZ', 11)
MATERIALIZED_EXT = os.environ.get(
    'ASAP_MATERIALZATED_EXT', "png")


TEST_MATERIALIZATION_JSON = {
    "project": MATERIALIZED_PROJECT,
    "stack": MATERIALIZED_STACK,
    "width": MATERIALIZED_IMAGE_WIDTH,
    "height": MATERIALIZED_IMAGE_HEIGHT,
    "minRow": MATERIALIZED_MINROW,
    "maxRow": MATERIALIZED_MAXROW,
    "minCol": MATERIALIZED_MINCOL,
    "maxCol": MATERIALIZED_MAXCOL,
    "minZ": MATERIALIZED_MINZ,
    "maxZ": MATERIALIZED_MAXZ,
    "ext": MATERIALIZED_EXT
}
